### ISSUE TITLE
Link to the random announcement (I'm feeling lucky!)

### ISSUE THREAD

**Issue by veelenga** [crystal-community/crystal-ann#50]
When user clicks on it, he will be redirected to a random **existed** announcement.

### TODOs:

- [ ] Create a new link on a side bar (below the search box) that directs to a random announcement (i.e. `/announcements/random`):

<img width="207" alt="screen shot 2017-10-04 at 9 45 11 am" src="https://user-images.githubusercontent.com/3624712/31163487-432f8df0-a8eb-11e7-8846-865ebf050fd1.png">

- [ ] Create a new [route](https://github.com/crystal-community/crystal-ann/blob/master/config/routes.cr) for `AnnouncementController#random`.
- [ ] Create a new action `random` in [`AnnouncementController`](https://github.com/crystal-community/crystal-ann/blob/master/src/controllers/announcement_controller.cr) that will redirect to `Announcements#show` with a random announcement id.
- [ ] Add tests for `Announcements#random`.
- [ ] Add yourself to the [contributors](https://github.com/crystal-community/crystal-ann#contributors) (if you are not there)
